### PR TITLE
Login page, styles, form and form submission, buttons, event handler,…

### PR DESCRIPTION
**Pull request by Naqi404**
… initial sample display all established. Initial working version of login and sign up page created as well as working requests with sample API calls.

### CODE REVIEW

**Review by nickquednow — CHANGES_REQUESTED** [review]
I would remove the registration part as it will be restricted to a specific group of people, and we will have the admins arrange for user account creation

**Comment by Naqi404** [comment]
Will adjust to convert the registration form into something else like a feedback or an access request form as the component is being used as a UI element atm.

**Comment by Naqi404** [comment]
Corrections pushed.

**Review by nickquednow — APPROVED** [review]
looks good

**Pull request merged**
